### ISSUE TITLE
Cannot authenticate user because admin user is not permitted to login via HTTP

### ISSUE THREAD

**Issue by skorup101** [jstakun/elastalert-ocp#1]
Hello,
I receive AuthorizationException(403, 'Cannot authenticate user because admin user is not permitted to login via HTTP') during startup from elastalert-ocp pod.
Do you know if there is a setting I should change in order for it to work?

**SETUP:**

**Openshift version:** 4.5.13

**Changes I made to original .yaml file:**
```
# git diff
diff --git a/elastalert-ocp.yaml b/elastalert-ocp.yaml
index 085d0e2..f1e378a 100644
--- a/elastalert-ocp.yaml
+++ b/elastalert-ocp.yaml
@@ -79,7 +79,7 @@ items:
         from:
           kind: ImageStreamTag
           name: elastalert-ocp:v0.2.1
-          namespace: openshift-elastalert
+          namespace: openshift-hselastalert
       type: ImageChange
 - apiVersion: apps.openshift.io/v1
   kind: DeploymentConfig
@@ -152,7 +152,7 @@ items:
         from:
           kind: ImageStreamTag
           name: mailman:latest
-          namespace: openshift-elastalert
+          namespace: openshift-hselastalert
         lastTriggeredImage: quay.io/jstakun/fake-smtp@sha256:4494354dd70709390b997acfe41b5107a275a4a3aaab6f91dea3a3955d3c19dd
       type: ImageChange
 - apiVersion: v1
```

**Error logs from elastalert-ocp pod:**
```
#oc logs -n openshift-hselastalert pod/elastalert-ocp-1-2fg2j
Traceback (most recent call last):
  File "/opt/app-root/bin/elastalert-create-index", line 10, in <module>
    sys.exit(main())
  File "/opt/app-root/lib/python3.6/site-packages/elastalert/create_index.py", line 264, in main
    create_index_mappings(es_client=es, ea_index=index, recreate=args.recreate, old_ea_index=old_index)
  File "/opt/app-root/lib/python3.6/site-packages/elastalert/create_index.py", line 23, in create_index_mappings
    esversion = es_client.info()["version"]["number"]
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 259, in info
    return self.transport.perform_request("GET", "/", params=params)
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch/transport.py", line 350, in perform_request
    timeout=timeout,
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch/connection/http_requests.py", line 156, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 181, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.AuthorizationException: AuthorizationException(403, 'Cannot authenticate user because admin user is not permitted to login via HTTP')
```
Thanks

**Comment by jstakun** [comment]
Hello
This seems to be an issue related to early versions of OpenShift 4.5: https://bugzilla.redhat.com/show_bug.cgi?id=1907758. I'll be able to test it with OpenShift 4.5 in a couple of days. 
So far I suggest to upgrade OCP 4.5 to newer z version and also upgrade Elasticsearch operator. 
You can modify ES connection configuration in config-cm config map. All certs referenced in config-cm config map are stored in elasticsearch secret.

**Comment by jstakun** [comment]
Finally I found the way to get it work on OCP 4.5+. 
I've created new branch https://github.com/jstakun/elastalert-ocp/tree/ocp-4.5+ containing new configuration and instructions. 
1. Use new elastalert-ocp:v0.2.4 image
2. Switch from client cert to bearer authentication to elasticsearch
2.1 In elastalert project create elastalert service account: oc create sa elastalert 
2.2 Comment out client_cert and client_key variables in cm-config config map
2.3 Add new es_bearer variable to cm-config config map containing elastalert token value: oc sa get-token elastalert 
3. For each elasticsearch pod in openshift-logging project add elastalert service account to sg_role_admin as per new README: https://github.com/jstakun/elastalert-ocp/blob/ocp-4.5%2B/README.md

**Comment by skorup101** [comment]
Hello Jarosław,

Thank you for your response.
